# Generated by Django 5.2.3 on 2025-06-19 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Création'), ('viewed', 'Consultation'), ('modified', 'Modification'), ('signed', 'Signature'), ('downloaded', 'Téléchargement')], max_length=20, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Activité de document',
                'verbose_name_plural': 'Activités de documents',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQRPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/prepared/', verbose_name='Fichier document')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('qr_x_position', models.FloatField(verbose_name='Position X du QR code')),
                ('qr_y_position', models.FloatField(verbose_name='Position Y du QR code')),
                ('qr_size', models.CharField(default='medium', max_length=20, verbose_name='Taille du QR code')),
                ('qr_pages', models.CharField(default='all', max_length=255, verbose_name='Pages avec QR code')),
                ('qr_positions', models.JSONField(blank=True, default=dict, null=True, verbose_name='Positions du QR code par page')),
                ('qr_mode', models.CharField(default='standard', max_length=20, verbose_name='Mode de positionnement')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_signature', 'En attente de signature'), ('signed', 'Signé'), ('rejected', 'Rejeté')], default='draft', max_length=20, verbose_name='Statut')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Position QR de document',
                'verbose_name_plural': 'Positions QR de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID du document')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre du document')),
                ('signer_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle du signataire')),
                ('original_file', models.FileField(upload_to='signatures/original/', verbose_name='Fichier original')),
                ('signed_file', models.FileField(upload_to='signatures/signed/', verbose_name='Fichier signé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('original_hash', models.CharField(blank=True, default='', max_length=255, verbose_name='Hash du document original')),
                ('signature', models.TextField(blank=True, default='', help_text='Signature en base64', verbose_name='Signature')),
                ('public_key_pem', models.TextField(blank=True, default='', verbose_name='Clé publique PEM')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Signature de document',
                'verbose_name_plural': 'Signatures de documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
