# Generated by Django 5.2.3 on 2025-06-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentqrposition',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/images/', verbose_name='Image de signature'),
        ),
        migrations.AddField(
            model_name='documentqrposition',
            name='signature_positions',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Positions de la signature par page'),
        ),
        migrations.AddField(
            model_name='documentqrposition',
            name='signature_size',
            field=models.IntegerField(blank=True, default=50, null=True, verbose_name='Taille de la signature en %'),
        ),
    ]
