# Generated by Django 5.2.3 on 2025-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentqrposition_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'organisation"),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du signataire'),
        ),
    ]
