# Generated by Django 5.2.4 on 2025-07-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_add_generated_pdf'),
        ('documents', '0005_add_signature_type_and_expiration'),
    ]

    operations = [
    ]
