# Generated by Django 5.2.3 on 2025-06-19 09:34

import signature_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'organisation")),
                ('user_role', models.CharField(blank=True, max_length=100, null=True, verbose_name="Rôle de l'utilisateur")),
                ('organization_role', models.CharField(blank=True, max_length=100, null=True, verbose_name="Rôle dans l'organisation")),
                ('original_document', models.FileField(upload_to=signature_templates.models.template_original_path, verbose_name='Document original')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=signature_templates.models.template_signature_path, verbose_name='Image de signature')),
                ('preview_document', models.FileField(blank=True, null=True, upload_to=signature_templates.models.template_preview_path, verbose_name='Aperçu du document')),
                ('qr_size', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=10, verbose_name='Taille du QR code')),
                ('page_application', models.CharField(choices=[('all', 'Toutes les pages (même position)'), ('current', 'Page actuelle uniquement'), ('custom', 'Pages personnalisées (même position)'), ('individual', 'Position individuelle par page')], default='all', max_length=20, verbose_name='Application des pages')),
                ('qr_positions', models.JSONField(default=dict, verbose_name='Positions du QR code')),
                ('signature_positions', models.JSONField(blank=True, default=dict, null=True, verbose_name='Positions de la signature')),
                ('selected_pages', models.JSONField(blank=True, default=list, null=True, verbose_name='Pages sélectionnées')),
                ('signature_size', models.IntegerField(default=50, verbose_name='Taille de la signature (%)')),
            ],
            options={
                'verbose_name': 'Template de signature',
                'verbose_name_plural': 'Templates de signature',
                'ordering': ['-created_at'],
            },
        ),
    ]
